services:
  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - monitor

  # Certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email hongdat.dev@gmail.com --agree-tos --no-eff-email
      -d grafana.hongdat.io.vn"

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    restart: unless-stopped
    command: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot && nginx -s reload; sleep 43200; done"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - nginx
    networks:
      - monitor

  # Monitoring service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/:/prometheus
    restart: unless-stopped
    networks:
      - monitor

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
    networks:
      - monitor

  # Visualize metrics
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000"
    volumes:
      - ./monitoring/grafana/:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitor

networks:
  monitor:
    driver: bridge
